// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;

namespace Wordzilla
{
	public partial class UICustomProgressBar : UIView
	{
		public static readonly UINib Nib = UINib.FromName ("UICustomProgressBar", NSBundle.MainBundle);

		public void Config (int cardid)
		{

		}


		public UICustomProgressBar (IntPtr handle) : base (handle)
		{

		}

		public static UICustomProgressBar Create ()
		{
			return (UICustomProgressBar)Nib.Instantiate (null, null) [0];
		}

		// progressbar
		public RectangleF ProgressBarPlace {
			get {
				return UICustomProgress.Frame;
			}
			set{
				UICustomProgress.Frame=value;
			}
		}
		public RectangleF ProgressBarGreen {
			get {
				return UICustomGreen.Frame;
			}
			set{
				UICustomGreen.Frame=value;
			}
		}
		public RectangleF ProgressBarRed {
			get {
				return UICustomRed.Frame;
			}
			set{
				UICustomRed.Frame=value;
			}
		}
		public RectangleF ProgressBarYellow {
			get {
				return UICustomYellow.Frame;
			}
			set{
				UICustomYellow.Frame=value;
			}
		}
		public RectangleF ProgressBarSilver {
			get {
				return UICustomSilver.Frame;
			}
			set{
				UICustomSilver.Frame=value;
			}
		}
		// /progressbar

		//[Export ("initWithFrame:")]
		/*	public UIBookCell (RectangleF frame) : base (frame)
			{
				BackgroundColor = UIColor.Cyan;
				ImageView = new UIImageView (Bounds);
				ImageView.AutoresizingMask = UIViewAutoresizing.FlexibleHeight | UIViewAutoresizing.FlexibleWidth;
				ImageView.ContentMode = UIViewContentMode.ScaleAspectFill;
				ImageView.Layer.BorderWidth = 3.0f;
				ImageView.ClipsToBounds = true;
				ImageView.Layer.BorderColor = UIColor.White.CGColor;
				ImageView.Layer.EdgeAntialiasingMask = CAEdgeAntialiasingMask.LeftEdge | CAEdgeAntialiasingMask.RightEdge | CAEdgeAntialiasingMask.BottomEdge | CAEdgeAntialiasingMask.TopEdge;
				ContentView.AddSubview (ImageView);
			}*/
	}
}
